server:
  port: 8084
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.203.128:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka